Feat/words list
FSD-For-Self-Dev/LinguistaAPI pull request #24
Opened 2023-09-14 16:15 UTC by Alfrederick888

add search, pagination

2023-09-28 09:07 UTC, BU-Marina requested changes
Нужно поправить

2023-09-28 09:07 UTC, BU-Marina commented on vocabulary/views.py
> +    ordering = ('-created', '-text',
Между полями ordering и ordering_fields есть разница: ordering это сортировка списка по умолчанию, а ordering_fields поля, по которым пользователь при желании может задать сортировку, исправь это пожалуйста - сделай ordering = ('-created',), а в ordering_fields перенеси все что сейчас у тебя в ordering

2023-09-28 09:07 UTC, BU-Marina commented on vocabulary/views.py
> +    search_fields = [
Сохраняй codestyle - если в других настройках используешь tuple, то и здесь тоже используй его, а не list, выше кстати тоже нужно заменить списки на кортежи

2023-09-28 09:07 UTC, BU-Marina commented on vocabulary/views.py
>      # ordering_fields = (
Эти комменты можно убрать

2023-09-28 09:07 UTC, BU-Marina commented on vocabulary/views.py
> +class CollectionViewSet(viewsets.ModelViewSet):
Не нужно в этой же ветке делать другие задачи, так все перемешается, для списка коллекций есть своя ветка, перенеси этот вьюсет и сериализатор в нее

2023-09-28 15:05 UTC, Alfrederick888 commented on config/settings.py
О каких настройках речь?

2023-09-28 15:06 UTC, Alfrederick888 commented on vocabulary/serializers.py
> +        fields = ('title', 'words',
В других моделях тоже по разному

2023-10-09 09:34 UTC, BU-Marina approved these changes

2023-10-09 09:34 UTC, merged