Feat/word crd
FSD-For-Self-Dev/LinguistaAPI pull request #26
Opened 2023-09-19 18:42 UTC by lmashik

# Story Title

[This is the Issue Title](https://github.com/username/repository-name/issues/1)

## Changes made

Апдейт кода для создания, получения и удаления слова.   
Это не финальная версия, но предварительно создание работает на примере   
```bash
curl --location 'http://127.0.0.1:8000/api/vocabulary/' \
--header 'Authorization: Token <token>' \
--header 'Content-Type: application/json' \
--header 'Cookie: csrftoken=<csrftoken>' \
--data '{
    "text": "to love",
    "translations": [
        {
            "text": "любить"
        }
    ],
    "examples": [
        {
            "text": "she loves flowers",
            "translation": "она любит цветы"
        }
    ],
    "definitions": [
        {
            "text": "to like smth or smbd a lot",
            "translation": "кто-то или что-то очень сильно нравится"
        }
    ],
    "is_problematic": true,
    "synonyms": [
        {
            "text": "to like",
            "translations": [
                {
                    "text": "нравиться"
                }
            ]
        }
    ],
    "antonyms": [
        {
            "text": "to hate",
            "translations": [
                {
                    "text": "ненавидеть"
                }
            ]
        }
    ],
    "forms": [
        {
            "text": "loves",
            "translations": [
                {
                    "text": "любит"
                },
                {
                    "text": "обожает"
                }
            ]
        },
        {
            "text": "loved",
            "translations": [
                {
                    "text": "любил(а)"
                }
            ]
        }
    ]
}'
```
Пока не реализовано все, что касается синонимов, антонимов, форм и похожих слов. Не могу сообразить, как их добавить, из-за того, что они тоже соответствуют модели слова, но продолжу думать. И тестировать)  
На мердж пока не претендую, но решила отправить уже хотя бы превью

п.с. честно признаться, я по ходу дела правила кавычки, докстринги, импорты и пр. легко верну все к исходному состоянию, если договоримся использовать определенный способ всего этого

## How does the solution address the problem

## Linked issues

Resolves #1

2023-09-23 00:08 UTC, lmashik commented
небольшой апдейт: работает добавление нового слова с синонимами (сами синонимы не создаются, создается только связь с ними)

пример тела запроса для теста (слово-синоним "to like" должно быть предварительно создано): 
```json
{
    "text": "to love",
    "translations": [
        {
            "text": "любить"
        },
        {
            "text": "обожать"
        }
    ],
    "examples": [
        {
            "text": "she loves flowers",
            "translation": "она любит цветы"
        }
    ],
    "definitions": [
        {
            "text": "to like smth or smbd a lot",
            "translation": "кто-то или что-то очень сильно нравится"
        }
    ],
    "is_problematic": true,
    "synonyms": [
        {
            "text": "to like",
            "translations": [
                {
                    "text": "нравиться"
                }
            ]
        }
    ]
}
```

2023-09-23 01:03 UTC, lmashik commented
но после создания слова оно возвращается без синонимов, антонимов, и пр. пока не знаю, почему 

(они там точно есть, но почему-то не сериализуются)

2023-09-28 11:19 UTC, BU-Marina requested changes
Все супер, но есть пара замечаний

2023-09-28 11:19 UTC, BU-Marina commented on vocabulary/serializers.py
> +    type = serializers.StringRelatedField()
Типов может быть несколько (бывает что слово одновременно и сущ, и глагол и пр.)
Нужно сделать их по аналогии с тегами

2023-09-28 11:19 UTC, BU-Marina commented on vocabulary/serializers.py
> +        definition_objs = [Definition(**data) for data in definitions]
Код дублируется, нужно сделать доп метод
Пока только два дубля, но потом их может быть больше

2023-09-28 11:19 UTC, BU-Marina commented on vocabulary/serializers.py
> +        for antonym in antonyms:
Тут тоже дублирование, тоже нужен доп метод

2023-09-28 11:19 UTC, BU-Marina commented on vocabulary/serializers.py
> +            'notes'
Теги и типы тоже можно добавить во множ. добавлении (мой косяк, забыла про них написать)

2023-09-28 11:19 UTC, BU-Marina commented on vocabulary/views.py
> +            return user.vocabulary.all().annotate(
Здесь нужно вернуть как было (писала про это в сериализаторах)

2023-09-28 11:19 UTC, BU-Marina commented on vocabulary/views.py
> +                    # author=request.user,
Почему закомментила автора?

2023-09-28 11:31 UTC, lmashik commented on config/settings.py
> +    # 'ACCESS_TOKEN_LIFETIME': timedelta(minutes=45),
там же есть просто вторая строка с более долгим скором, поэтому закомментировала чисто для своего удобства, конечно, можно убрать обратно, забыла про это

2023-09-28 11:31 UTC, lmashik commented on vocabulary/models.py
> +        # related_name='antonym_to+',
ага

2023-09-28 11:31 UTC, lmashik commented on vocabulary/serializers.py
> +    translations_count = serializers.SerializerMethodField()
SerializerMethodField писала не я, он уже был, заменю

2023-09-28 11:31 UTC, lmashik commented on vocabulary/serializers.py
> +        definition_objs = [Definition(**data) for data in definitions]
ага, над этим подумаю

2023-09-28 11:32 UTC, lmashik commented on vocabulary/serializers.py
> +            'notes'
надо ли так много всего во множественном добавлении? сложно как-то выходит

2023-09-28 11:32 UTC, lmashik commented on vocabulary/views.py
> +            return user.vocabulary.all().annotate(
это тоже не моя правка, я ее стянула из девелоп, эти две строки не трогала. но сейчас стянула последние изменения и это исчезло уже

2023-09-28 11:33 UTC, lmashik commented on vocabulary/views.py
> +                    # author=request.user,
потому что если он уже приходит из сериализатора. если его оставить еще и тут, то будет ошибка, что автор не один

2023-09-28 14:52 UTC, lmashik commented on vocabulary/serializers.py
> +        if Word.objects.filter(author=author_id, text=text).exists():
вроде как правильно делать валидацию не только в модели, но и в сериализаторе, или я ошибаюсь?

2023-09-29 16:44 UTC, lmashik commented on vocabulary/serializers.py
> +        definition_objs = [Definition(**data) for data in definitions]
не могу сообразить, как сделать общий метод, если в промежуточных таблицах поля называются по-разному - example и definition

2023-09-29 16:58 UTC, lmashik commented on vocabulary/serializers.py
> +        definition_objs = [Definition(**data) for data in definitions]
![image_2023-09-29_19-55-55](https://github.com/FSD-For-Self-Dev/LinguistaAPI/assets/110331711/61bd1635-46de-456f-b543-694012f23770)
я вот об этом

2023-09-29 17:47 UTC, lmashik commented on vocabulary/serializers.py
> +        definition_objs = [Definition(**data) for data in definitions]
вопрос снят, я все сделала)))

2023-10-06 15:02 UTC, lmashik commented
надеюсь, мы как никогда близко к закрытию задачки ))) 

поправила все по комментам и даже синонимы и прочие ворды теперь сериализуются 

примеры запросов

```bash
curl --location 'http://127.0.0.1:8000/api/vocabulary/' \
--header 'Authorization: Token 12f3471fadb9ff651be5d2baab3335ea0d32c2f5' \
--header 'Content-Type: application/json' \
--header 'Cookie: csrftoken=yfppnYXyk543NlUty3M9qjBHytA3scGB' \
--data '{
    "language": "English",
    "text": "to love",
    "translations": [
        {
            "text": "любить"
        },
        {
            "text": "обожать"
        }
    ],
    "examples": [
        {
            "text": "she loves flowers",
            "translation": "она любит цветы"
        }
    ],
    "definitions": [
        {
            "text": "to like smth or smbd a lot",
            "translation": "кто-то или что-то очень сильно нравится"
        }
    ],
    "is_problematic": true,
    "synonyms": [
        {
            "text": "to like",
            "translations": [
                {
                    "text": "нравиться"
                }
            ]
        }
    ],
    "antonyms": [
        {
            "text": "to hate",
            "translations": [
                {
                    "text": "нравиться"
                }
            ]
        }
    ],
    "forms": [
        {
            "text": "loved",
            "translations": [
                {
                    "text": "нравиться"
                }
            ]
        }
    ],
    "similars": [
        {
            "text": "to laugh",
            "translations": [
                {
                    "text": "нравиться"
                }
            ]
        }
    ],
    "notes": [
        {
            "text": "обязательно выучить"
        }
    ],
    "tags": [
        1
    ],
    "types": [
        1, 2
    ],
    "collections": [
        1
    ]
}'
```

и еще один маленький

```bash
curl --location 'http://127.0.0.1:8000/api/vocabulary/' \
--header 'Authorization: Token 12f3471fadb9ff651be5d2baab3335ea0d32c2f5' \
--header 'Content-Type: application/json' \
--header 'Cookie: csrftoken=yfppnYXyk543NlUty3M9qjBHytA3scGB' \
--data '{
    "text": "big fish",
    "translations": [
        {
            "text": "большая рыба"
        }
    ],
    "notes": [
        {
            "text": "обязательно выучить"
        }
    ]
}'
```

2023-10-06 18:45 UTC, BU-Marina requested changes
Супер, большая работа проделана, все отлично сделала! Осталось только пара моментиков, больше стилевых

2023-10-06 19:58 UTC, lmashik commented on vocabulary/serializers.py
> +        ret = value.name
это я зачем-то переняла стиль доки джанги, там это классическая реализация этих методов поля) 

согласна, здесь лишнее

2023-10-06 20:15 UTC, lmashik commented on vocabulary/serializers.py
> +        if len(translations) > MAX_TRANSLATIONS_AMOUNT:
не знаю ))) почему-то решила, что раз две проверки для переводов, то нельзя )))

2023-10-06 20:34 UTC, lmashik commented on vocabulary/constants.py
> +    r'^[A-Za-zА-Яа-я0-9\-\!\?]+'
ага, хорошо

тогда из ТЗ надо тоже убрать, на него ориентировалась для валидации

2023-10-06 20:35 UTC, lmashik commented on vocabulary/constants.py
> +    r'^[A-Za-zА-Яа-я0-9\-\!\?]+'
слушай, мои глаза странным образом увидели где-то цифры в ТЗ. сейчас увидела, что их там нет. прошу прощения)

2023-10-09 08:41 UTC, BU-Marina approved these changes

2023-10-09 08:42 UTC, merged