Collection CRD
FSD-For-Self-Dev/LinguistaAPI pull request #36
Opened 2023-10-02 08:50 UTC by OneHandedPirate

- add slug field to Collection model;
- add prepopulated_fields to Collection model admin registration for slug generation;
- add Collection serializer
- add IsAuthorOrReadOnly custom permission
- add CollectiomViewSet

2023-10-18 09:18 UTC, BU-Marina requested changes
Класс, но есть пара комментариев

2023-10-18 09:18 UTC, BU-Marina commented on vocabulary/admin.py
> +admin.site.register(Collection, CollectionAdmin)
Можно сделать это декоратором @admin.register(Collection) над CollectionAdmin, но вроде разницы нет

2023-10-18 09:18 UTC, BU-Marina commented on vocabulary/permissions.py
> +        if request.method in permissions.SAFE_METHODS:
Можно заменить одной строчкой `return request.method in permissions.SAFE_METHODS or obj.author == request.user`, но не принципиально

2023-10-18 09:18 UTC, BU-Marina commented on vocabulary/views.py
> +        return user.collections
Нужно аннотировать кол-вом слов в каждой коллекции `words_count`

2023-10-18 09:18 UTC, BU-Marina commented on vocabulary/views.py
> +    ordering = ('-created',)
Нарушен стиль скобок, выше списки а в ordering кортеж, во вьюсете слова у нас все кортежи, давай тут тоже все круглые скобки сделаем

2023-10-18 09:18 UTC, BU-Marina commented on vocabulary/serializers.py
> +        fields = ('id', 'author', 'title', 'description', 'words', 'created', 'modified')
Тут бы указать напрямую read_only_fields и нужно еще сделать перенос, слишком длинная строка

2023-10-19 07:47 UTC, OneHandedPirate commented on vocabulary/permissions.py
> +        if request.method in permissions.SAFE_METHODS:
Так немного читаемость страдает, но ок.

2023-10-24 09:08 UTC, BU-Marina approved these changes

2023-10-24 09:14 UTC, merged